[project]
name = "repl-nix-llm-chunkoptimizer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.54.0",
    "plotly>=5.24.1",
    "streamlit>=1.39.0",
]
